experiment:
  name: AP 36.2.9_beta3
  log_dir: ./results/APCNN
  seed: 42
dataset:
  name: cub
  root_dir: data/bird/CUB_200_2011/images
  meta_dir: metadata/cub
  batch_size: 16
  num_workers: 2
  transformer:
    image_size: 448
    resize_size: 512
model:
  name: APCNN
  num_classes: 200
train:
  cuda: [5]
  epoch: 100
  save_frequence: 100
  optimizer:
    name: SGD
    lr: 0.0005
    weight_decay: 0.0005
  scheduler:
    name: origin_code
  criterion:
    name: CrossEntropyLoss

