experiment:
  log_dir: results/CBCNN
  name: CBP3 S1=5.2 repeat_3
  seed: 0
dataset:
  name: cub
  root_dir: data/bird/CUB_200_2011/images
  meta_dir: metadata/cub
  batch_size: 16
  num_workers: 4
  transformer:
    image_size: 224
    resize_size: 256
model:
  name: CBCNN
  stage: 1  # Training stage for CBCNN. Stage 1 freeze backbone parameters.
  num_classes: 200
  input_channel: 512    # input dimension of compact bilinear pooling.
  output_channel: 6000  # output dimension of compact bilinear pooling.
train:
  cuda: [0]
  epoch: 120
  save_frequence: 120
  optimizer:
    name: SGD
    lr: 2.0
    momentum: 0.9
    weight_decay: 0.00000001
  scheduler:
    T_max: 120
    warmup_epochs: 5
    lr_warmup_decay: 0.01
  criterion:
    name: CrossEntropyLoss
